### ISSUE TITLE
FR: option to copy coordinates when copying objects between steps

### ISSUE THREAD

**Issue by tcoren** [joelspadin/xivplan#31]
When copying an object/icon from one step to another, it would be helpful if the position of the object within the arena would be unchanged, instead of pasting to the cursor location (i.e. the offset would be 0).
If you do not desire to change the default behavior, an option to do this would still be greatly appreciated, i.e. by making a shortcut like ctrl+shift+V be "copy without changing location" (this could also be implemented via the ctrl+D "duplicate selected objects" feature).
This option would make it far easier to correct mistakes in multiple steps whilst keeping positions consistent, e.g. correcting the position of an object in multiple steps, adding a missing marker to all steps, etc.
Preferably this feature would also work when copying multiple objects.

**Comment by joelspadin** [comment]
Duplicate with Ctrl+D already exists and would normally be the shortcut for this, but that doesn't work here because as soon as you switch steps, there aren't any selected objects anymore. I'll have to decide on what the best keyboard shortcut and name for this is, but I think having a way to duplicate the objects that are on the clipboard would be useful and not hard to implement.

**Comment by joelspadin** [comment]
This is now implemented with the shortcut Ctrl+Shift+V
