### ISSUE TITLE
Sharing & Rearrange Slides

### ISSUE THREAD

**Issue by IrulanSB** [joelspadin/xivplan#8]
I am requesting two features.

1. I would like to rearrange the slides.
Often when making a plan, I end up having to delete slides to be able to rearrange them in the order I want. It would be nice to drag or re-order them in any way.

2. Sharing Issues

2.1 When sharing, the link is too long for discord. Discord is heavily used by raiding groups to communicate, so it would be pleasant to directly link raid plans on there. Right now, links have to be posted as text files.

2.2 When I share a raid plan, the link I give goes to a static version of the plan, with no way to update the plan without giving a new link.
It would be nice to have some way to give one link and have that show the latest version of the plan. 
If this is not possible, then is it possible to label these plans with versions because right now it is hard to compare to see if the person is viewing an up-to-date plan or an old version. 

Thanks for the work put into this project.

**Comment by joelspadin** [comment]
Rearranging would be possible to implement, but I just need to come up with a good UI for it first. My current best idea is a dialog window that shows thumbnails of each step (like the arena presets window) and lets you drag and drop, then confirm so it all ends up as one change in the undo order.

The reason the link is so long and goes to a static version of the plan is because the link _is_ the plan. All of the data for the plan is encoded within the link. I don't store any data, nor do I _want_ to store data (because then I have to pay for storage, maybe deal with GDPR, etc.). If you check the other issues here, you'll see some discussions on ways we might be able to use 3rd party sites for storage, but I've been spending my free time on other things recently and haven't taken the time to figure that out yet.

Current workarounds for sharing issues:
1. The smaller your plan is, the more likely it is to fit in a Discord link. If you're currently making one plan for a whole fight, try breaking it into separate plans per mechanic.
2. Stick a text field onto the first step and write a version number there.

**Comment by IrulanSB** [comment]
I see, for the slide ui I think the ui for raidplan.io is solid as well.
They just have horizontal arrows the move the currently selected slide either 1 back or 1 forward.
It's crude but works extremely well.

As for the link, I understand. Np.

Lastly I think I read you saying that you prog blind. If so when selecting arenas/maps it should not show all phases. It should only show 1 at a time, so a player can not see how many phases there are.

Anyway Ty for all the good work.

**Comment by joelspadin** [comment]
> I see, for the slide ui I think the ui for raidplan.io is solid as well.
They just have horizontal arrows the move the currently selected slide either 1 back or 1 forward.
It's crude but works extremely well.

That was my first idea, but I think it would be hard to tell what you're doing and would potentially insert many unnecessary steps into the undo order.

> Lastly I think I read you saying that you prog blind. If so when selecting arenas/maps it should not show all phases. It should only show 1 at a time, so a player can not see how many phases there are.

So far I've just been assuming that everyone else is faster than my group. 🙂 I'll have to think of whether there's any good way to do that. I don't want to only show one thing at a time, because then if you _have_ gotten to a particular phase, that makes it take longer to set up a new plan for that phase.

I could set it up so you have to tell the app how far you've gotten, and it only shows arena presets up to that point, but then how do I let you choose that without giving away how many phases exist? My best idea so far is just "next fight" and "next phase" buttons for each raid tier, but even that is tricky. For example, if I only show the buttons when there are still phases left, then you'll know when you're on the last phase (that I've made a preset for).

A simpler idea would be to give each preset a more generic name that doesn't indicate a particular phase and blur each one out until you've clicked on it once. That would still give you some idea of how many variations in the arena occur in a fight, but it wouldn't let you see what they look like until you choose to look.

**Comment by joelspadin** [comment]
I've implemented rearranging slides and hiding potential spoiler info in arena presets. I think the only remaining request here is for a way to have a single link that contains an up-to-date version of the plan, which would be covered by #6 since I have no plans to start storing any data myself.

Feel free to create a new issue if there's any other unresolved part of this that I missed.
